# Generated by Django 4.2.6 on 2023-10-27 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_administrator_user_alter_police_admin_and_more'),
        ('police_stations', '0002_policestation_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policestation',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.customuser'),
        ),
    ]
