# Generated by Django 4.2.6 on 2023-10-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_joined',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
