# Generated by Django 4.2.6 on 2023-10-27 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('police_stations', '0001_initial'),
        ('authentication', '0004_customuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='police',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='police',
            name='police_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='police_stations.policestation'),
        ),
    ]
