# Generated by Django 4.2.6 on 2023-10-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_police_admin_police_police_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police',
            name='policeID',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
